services:
  emulator:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  service:
    image: redis
volumes:
  logvolume01: {}